## Numerical Python (Numpy) and Python Data Analysis (Pandas)

### To access Numpy library, the import convention must be used: import numpy as np

In [1]:
import numpy as np

x = np.array (argument)
np - the library


##### Python Demo 1: Creating and Inspecting ndrrays

In [2]:
#1D Array - vector
el = np.array([1,2,3])
el

# el = [1 2 3]

array([1, 2, 3])

### the number of [[[]]] will determine the number of arrays

In [3]:
#2D Array - matrix
psy = np.array([(2.4,-1.5,1.1), (2.3,-2.5,-5.6)])
psy

# psy = [2.4 -1.5 1.1
#        2.3 -2.5 -5.6]

array([[ 2.4, -1.5,  1.1],
       [ 2.3, -2.5, -5.6]])

In [4]:
#3D Array - tensor
kongroo = np.array([[(1.1,2,3.4),(7,2.5,9)],[(1,2,3),(9,8,7)]])
kongroo

array([[[1.1, 2. , 3.4],
        [7. , 2.5, 9. ]],

       [[1. , 2. , 3. ],
        [9. , 8. , 7. ]]])

In [5]:
#Create an array of m x n x p zeros
x = np.zeros((2,3)) #2 rows, 3 columns
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
y = np.ones((5,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#Syntax: np.arange(first:last-interval:interval)

z = np.arange(3,7,0.5) #the np.arange gives u the range from 3 - 7 but doesnt print the last digit
z

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [8]:
#Syntax: np.linspace(first:last:number of samples)
np.linspace(3,7,10) #the terminal value is printed, divides the interval equally, gives sample size

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

In [9]:
np.full((2,3),8) #((the size, size)the number that will be printed)

array([[8, 8, 8],
       [8, 8, 8]])

In [10]:
# identity matrix: np.eye(m)
np.eye(4) #an example of identity matrix, prints a diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.random((2,3)) #random values will be printed

array([[0.7297709 , 0.83750975, 0.84469961],
       [0.53688865, 0.38731977, 0.28546731]])

In [13]:
#Viewing the contents on a numpy file
#Syntax = np.load('filename.npy')
data = np.load('epk.npy')
data

#this pre-loads a file that is downloaded and saved in the same folder 


array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [14]:
data.shape #gives you the lengt,height, width

(2, 2, 3)

In [15]:
data.ndim

3

In [16]:
data.size

12

In [17]:
a = np.array([(2,4,6),(8,10,12)])
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [18]:
b = np.array([(4,9),(16,25),(36,49)])
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [19]:
c = np.array([2,3,5])
c

array([2, 3, 5])

In [20]:
#Element-wise, it subracts or add the corresponding columns and rows
c-a

array([[ 0, -1, -1],
       [-6, -7, -7]])

In [21]:
a+c

array([[ 4,  7, 11],
       [10, 13, 17]])

In [22]:
a*c

array([[ 4, 12, 30],
       [16, 30, 60]])

In [23]:
c*a

array([[ 4, 12, 30],
       [16, 30, 60]])

In [24]:
a/c

array([[1.        , 1.33333333, 1.2       ],
       [4.        , 3.33333333, 2.4       ]])

In [25]:
c/a

array([[1.        , 0.75      , 0.83333333],
       [0.25      , 0.3       , 0.41666667]])

In [26]:
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [27]:
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [28]:
np.exp(b)

array([[5.45981500e+01, 8.10308393e+03],
       [8.88611052e+06, 7.20048993e+10],
       [4.31123155e+15, 1.90734657e+21]])

In [29]:
np.sqrt(b)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [30]:
np.sin(b) #assumed to be in radians

array([[-0.7568025 ,  0.41211849],
       [-0.28790332, -0.13235175],
       [-0.99177885, -0.95375265]])

In [34]:
a = np.array([2, 3, 5])
a

array([2, 3, 5])

In [35]:
b = np.array([(1,2,5), (4,5,6), (7,8,9)])
b

array([[1, 2, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
# = is an assignment operator
c = a
c

array([2, 3, 5])

In [37]:
# element wise 
a ==b # outputs false if the values doesnt match

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [32]:
b < 7


array([[ True, False],
       [False, False],
       [False, False]])

In [38]:
a > 2

array([False,  True,  True])

In [39]:
#as a group
np.array_equal(a,b)

False

In [41]:
np.array_equal(a,c)

True

#### Python Demo 3: Subsetting, Slicing and Indexing of Arrays

In [42]:
A = np.array ([(1,2,3),(4,5,6),(7,8,9)])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Subsetting - getting a certain element from the array or structure, element lang hinahanap

In [43]:
A[1,1] #or A[1][1] brackets are the locator

5

In [44]:
A[2,1] #[row,column]

8

Slicing - getting the portion from an array or structure

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
A[1:3] #sandwich lang hindi sinasama yung last na index but its like a boundary

array([[4, 5, 6],
       [7, 8, 9]])

In [47]:
A[1]

array([4, 5, 6])

Indexing - is getting a certain element or portion depending on the conditions.

In [48]:
A[A<7]

array([1, 2, 3, 4, 5, 6])

In [49]:
A[A>2]

array([3, 4, 5, 6, 7, 8, 9])

In [50]:
A[A==5]

array([5])

#### Demo#4: ndarray manipulation

In [51]:
a = np.array([3,2,1])
a

array([3, 2, 1])

In [52]:
b = np.array([(4,6,5),(3,2,1)])
b

array([[4, 6, 5],
       [3, 2, 1]])

In [53]:
c = np.linspace(10,20,3)
c

array([10., 15., 20.])

In [54]:
d = np.full((2,2),7)

In [55]:
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [56]:
a.sort()
a

array([1, 2, 3])

In [57]:
b

array([[4, 6, 5],
       [3, 2, 1]])

In [58]:
b.sort(axis=0) #pag axis 0 by row
b

array([[3, 2, 1],
       [4, 6, 5]])

In [59]:
b.sort(axis=1) #pag axis 1 by column
b

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.shape(b)

(2, 3)

In [61]:
b.reshape(6,1).shape #.shape gives the shape itself but without it will produce a 1column with 6 rows
b

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
b.resize(6,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [63]:
d

array([[7, 7],
       [7, 7]])

In [64]:
e

array([[1., 0.],
       [0., 1.]])

In [65]:
np.append(d,e) #the array becomes 1 dimension

array([7., 7., 7., 7., 1., 0., 0., 1.])

In [66]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [68]:
np.delete(a,[2]) #doesnt change the original array as long as its not updated

array([1, 2])

In [69]:
np.concatenate((a,c), axis=0)

array([ 1.,  2.,  3., 10., 15., 20.])

In [70]:
np.vstack((a,c)) #connects vertically

array([[ 1.,  2.,  3.],
       [10., 15., 20.]])

In [71]:
np.hstack((d,e)) # connects horizontally

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [72]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [73]:
np.vsplit(e,2)

[array([[1., 0.]]), array([[0., 1.]])]